In [1]:
pip install pandas

Requirement already satisfied: pandas in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=2.3.3 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

excel_file = 'sales data.xlsx'

df = pd.read_excel(excel_file)

df.head()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,98320.37,77722.25,8/23/2020,Games,Konopelski LLC,Maxie Marrow,Tarrah Castelletti,Tablet,70-0511466
1,France,46296.26,40319.41,5/15/2020,Games,Wisoky Inc,Othello Bowes,Amelina Piscopiello,Tablet,77-3489084
2,Portugal,140337.34,115708.14,2020-04-09 00:00:00,Appliances,Hegmann Group,Celine Tumasian,Corene Shirer,PC,65-8218141
3,France,203604.46,175344.16,6/26/2019,Electronics,Kirlin and Sons,Othello Bowes,Crysta Halls,Mobile,29-5478106
4,UK,63979.04,56032.84,10/22/2019,Games,Schoen-Keeling,Jessamine Apark,Genevra Charrisson,PC,27-3437546

In [3]:
import pandas as pd

excel_file = 'sales data.xlsx'

df = pd.read_excel(excel_file)

df.head()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,98320.37,77722.25,8/23/2020,Games,Konopelski LLC,Maxie Marrow,Tarrah Castelletti,Tablet,70-0511466
1,France,46296.26,40319.41,5/15/2020,Games,Wisoky Inc,Othello Bowes,Amelina Piscopiello,Tablet,77-3489084
2,Portugal,140337.34,115708.14,2020-04-09 00:00:00,Appliances,Hegmann Group,Celine Tumasian,Corene Shirer,PC,65-8218141
3,France,203604.46,175344.16,6/26/2019,Electronics,Kirlin and Sons,Othello Bowes,Crysta Halls,Mobile,29-5478106
4,UK,63979.04,56032.84,10/22/2019,Games,Schoen-Keeling,Jessamine Apark,Genevra Charrisson,PC,27-3437546

In [4]:
!pip install openpyxl

Requirement already satisfied: openpyxl in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from openpyxl) (2.0.0)

In [5]:
import pandas as pd

df = pd.read_excel("Practice datasets/sales data.xlsx")
df.head()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,98320.37,77722.25,8/23/2020,Games,Konopelski LLC,Maxie Marrow,Tarrah Castelletti,Tablet,70-0511466
1,France,46296.26,40319.41,5/15/2020,Games,Wisoky Inc,Othello Bowes,Amelina Piscopiello,Tablet,77-3489084
2,Portugal,140337.34,115708.14,2020-04-09 00:00:00,Appliances,Hegmann Group,Celine Tumasian,Corene Shirer,PC,65-8218141
3,France,203604.46,175344.16,6/26/2019,Electronics,Kirlin and Sons,Othello Bowes,Crysta Halls,Mobile,29-5478106
4,UK,63979.04,56032.84,10/22/2019,Games,Schoen-Keeling,Jessamine Apark,Genevra Charrisson,PC,27-3437546

In [6]:
missing_values = df.isnull().sum()

In [7]:
print("Missing Values")
print(missing_values[missing_values > 0])

Missing Values
order_value_EUR    5
device_type        5
dtype: int64

In [8]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (2.4.2)
Requirement already satisfied: scipy>=1.10.0 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [10]:
from sklearn.impute import SimpleImputer


target_column = 'order_value_EUR'

imputer = SimpleImputer(strategy='median')

df[target_column] = imputer.fit_transform(df[[target_column]])

In [11]:
import pandas as pd

df = pd.read_excel("Practice datasets/sales data.xlsx")

df.head()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,98320.37,77722.25,8/23/2020,Games,Konopelski LLC,Maxie Marrow,Tarrah Castelletti,Tablet,70-0511466
1,France,46296.26,40319.41,5/15/2020,Games,Wisoky Inc,Othello Bowes,Amelina Piscopiello,Tablet,77-3489084
2,Portugal,140337.34,115708.14,2020-04-09 00:00:00,Appliances,Hegmann Group,Celine Tumasian,Corene Shirer,PC,65-8218141
3,France,203604.46,175344.16,6/26/2019,Electronics,Kirlin and Sons,Othello Bowes,Crysta Halls,Mobile,29-5478106
4,UK,63979.04,56032.84,10/22/2019,Games,Schoen-Keeling,Jessamine Apark,Genevra Charrisson,PC,27-3437546

In [12]:
from sklearn.impute import SimpleImputer

target_column = 'order_value_EUR'

imputer = SimpleImputer(strategy='median')
df[target_column] = imputer.fit_transform(df[[target_column]])

In [13]:
df.isnull().sum()

country            0
order_value_EUR    0
cost               0
date               0
category           0
customer_name      0
sales_manager      0
sales_rep          0
device_type        5
order_id           0
dtype: int64

In [15]:
df.device_type

0       Tablet
1       Tablet
2           PC
3       Mobile
4           PC
         ...
996         PC
997     Tablet
998     Tablet
999         PC
1000        PC
Name: device_type, Length: 1001, dtype: str

In [18]:
import pandas as pd
df = pd.read_excel("Practice datasets/sales data.xlsx")

In [21]:
from sklearn.impute import SimpleImputer

target_column = 'device_type'

imputer = SimpleImputer(strategy='most_frequent')
df[target_column] = imputer.fit_transform(df[[target_column]]).ravel()

In [22]:
df.isnull().sum()

country            0
order_value_EUR    5
cost               0
date               0
category           0
customer_name      0
sales_manager      0
sales_rep          0
device_type        0
order_id           0
dtype: int64

In [23]:
#getting data types

data_types = df.dtypes

print("Data Types:")
print(data_types)

Data Types:
country                str
order_value_EUR    float64
cost                object
date                object
category               str
customer_name          str
sales_manager          str
sales_rep              str
device_type            str
order_id               str
dtype: object

In [27]:
mixed_data = df['cost']

#create an empty list for non_numeric values
non_numeric_values = []

#checking variables' data types(cost)

for value in mixed_data:
    if isinstance(value, str) and not value.isnumeric():
        non_numeric_values.append(value)

print ("Non_numeric Values:")
print(non_numeric_values)

Non_numeric Values:
[]

In [26]:
#removing value that is not the of variable's datatype
#specify variable(column)
numeric_column ='cost'

#define value to search and remove
value_to_remove = 'XXX'

#create a boolean mask to identify rows where the specified value is in the column
mask =(df[numeric_column]== value_to_remove)

df = df[~mask]

print(df)

          country  order_value_EUR       cost                 date  \
0          Sweden         98320.37   77722.25            8/23/2020
1          France         46296.26   40319.41            5/15/2020
2        Portugal        140337.34  115708.14  2020-04-09 00:00:00
3          France        203604.46  175344.16            6/26/2019
4              UK         63979.04   56032.84           10/22/2019
...           ...              ...        ...                  ...
996        France         69126.50    55902.6  2019-08-12 00:00:00
997        France        140943.88  120633.87            5/28/2020
998        France        124784.67  106853.11            5/22/2020
999       Germany         61968.26   50690.04           12/27/2020
1000  Netherlands        172453.10  145688.38            6/24/2020

         category                     customer_name    sales_manager  \
0           Games                    Konopelski LLC     Maxie Marrow
1           Games                        Wisoky Inc    Othello Bowes
2      Appliances                     Hegmann Group  Celine Tumasian
3     Electronics                   Kirlin and Sons    Othello Bowes
4           Games                    Schoen-Keeling  Jessamine Apark
...           ...                               ...              ...
996   Electronics     Farrell, Swaniawski and Crist    Othello Bowes
997    Appliances                  Armstrong-Little    Othello Bowes
998   Electronics  Swaniawski, Runolfsson and Green    Othello Bowes
999   Electronics                Romaguera-Dietrich  Rickard Doogood
1000     Outdoors                   Kirlin and Sons    Denice Amberg

                sales_rep device_type    order_id
0      Tarrah Castelletti      Tablet  70-0511466
1     Amelina Piscopiello      Tablet  77-3489084
2           Corene Shirer          PC  65-8218141
3            Crysta Halls      Mobile  29-5478106
4      Genevra Charrisson          PC  27-3437546
...                   ...         ...         ...
996        Avrit Chanders          PC  07-3201531
997        Avrit Chanders      Tablet  77-0650807
998           Ora Grennan      Tablet  44-2757396
999         Casie MacBain          PC  22-7259031
1000       Nero Harbisher          PC  60-6986682

[1000 rows x 10 columns]

In [28]:
#assigning datatype for 'cost'

df['cost'] = df['cost'].astype(float)

print(df.dtypes)

country                str
order_value_EUR    float64
cost               float64
date                object
category               str
customer_name          str
sales_manager          str
sales_rep              str
device_type            str
order_id               str
dtype: object

In [33]:
#assigning datatype for 'date'

df['date'] = pd.to_datetime(df['date'])

print(df.dtypes)

country                       str
order_value_EUR           float64
cost                      float64
date               datetime64[us]
category                      str
customer_name                 str
sales_manager                 str
sales_rep                     str
device_type                   str
order_id                      str
dtype: object

In [34]:
df.head()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,98320.37,77722.25,2020-08-23,Games,Konopelski LLC,Maxie Marrow,Tarrah Castelletti,Tablet,70-0511466
1,France,46296.26,40319.41,2020-05-15,Games,Wisoky Inc,Othello Bowes,Amelina Piscopiello,Tablet,77-3489084
2,Portugal,140337.34,115708.14,2020-04-09,Appliances,Hegmann Group,Celine Tumasian,Corene Shirer,PC,65-8218141
3,France,203604.46,175344.16,2019-06-26,Electronics,Kirlin and Sons,Othello Bowes,Crysta Halls,Mobile,29-5478106
4,UK,63979.04,56032.84,2019-10-22,Games,Schoen-Keeling,Jessamine Apark,Genevra Charrisson,PC,27-3437546

In [37]:
#dealing with duplicated values
#identify duplicate rows
duplicates = df[df.duplicated()]

print("Duplicates Rows:")
print(duplicates)

#remove duplicates
df_no_duplicates = df.drop_duplicates()

print("No duplicates:")
print(df_no_duplicates)

Duplicates Rows:
   country  order_value_EUR      cost       date category   customer_name  \
23      UK         63979.04  56032.84 2019-10-22    Games  Schoen-Keeling

      sales_manager           sales_rep device_type    order_id
23  Jessamine Apark  Genevra Charrisson          PC  27-3437546
No duplicates:
          country  order_value_EUR       cost       date     category  \
0          Sweden         98320.37   77722.25 2020-08-23        Games
1          France         46296.26   40319.41 2020-05-15        Games
2        Portugal        140337.34  115708.14 2020-04-09   Appliances
3          France        203604.46  175344.16 2019-06-26  Electronics
4              UK         63979.04   56032.84 2019-10-22        Games
...           ...              ...        ...        ...          ...
996        France         69126.50   55902.60 2019-08-12  Electronics
997        France        140943.88  120633.87 2020-05-28   Appliances
998        France        124784.67  106853.11 2020-05-22  Electronics
999       Germany         61968.26   50690.04 2020-12-27  Electronics
1000  Netherlands        172453.10  145688.38 2020-06-24     Outdoors

                         customer_name    sales_manager            sales_rep  \
0                       Konopelski LLC     Maxie Marrow   Tarrah Castelletti
1                           Wisoky Inc    Othello Bowes  Amelina Piscopiello
2                        Hegmann Group  Celine Tumasian        Corene Shirer
3                      Kirlin and Sons    Othello Bowes         Crysta Halls
4                       Schoen-Keeling  Jessamine Apark   Genevra Charrisson
...                                ...              ...                  ...
996      Farrell, Swaniawski and Crist    Othello Bowes       Avrit Chanders
997                   Armstrong-Little    Othello Bowes       Avrit Chanders
998   Swaniawski, Runolfsson and Green    Othello Bowes          Ora Grennan
999                 Romaguera-Dietrich  Rickard Doogood        Casie MacBain
1000                   Kirlin and Sons    Denice Amberg       Nero Harbisher

     device_type    order_id
0         Tablet  70-0511466
1         Tablet  77-3489084
2             PC  65-8218141
3         Mobile  29-5478106
4             PC  27-3437546
...          ...         ...
996           PC  07-3201531
997       Tablet  77-0650807
998       Tablet  44-2757396
999           PC  22-7259031
1000          PC  60-6986682

[999 rows x 10 columns]

In [38]:
cleaned_data = df_no_duplicates

In [39]:
cleaned_data.head()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,98320.37,77722.25,2020-08-23,Games,Konopelski LLC,Maxie Marrow,Tarrah Castelletti,Tablet,70-0511466
1,France,46296.26,40319.41,2020-05-15,Games,Wisoky Inc,Othello Bowes,Amelina Piscopiello,Tablet,77-3489084
2,Portugal,140337.34,115708.14,2020-04-09,Appliances,Hegmann Group,Celine Tumasian,Corene Shirer,PC,65-8218141
3,France,203604.46,175344.16,2019-06-26,Electronics,Kirlin and Sons,Othello Bowes,Crysta Halls,Mobile,29-5478106
4,UK,63979.04,56032.84,2019-10-22,Games,Schoen-Keeling,Jessamine Apark,Genevra Charrisson,PC,27-3437546

In [41]:
#sorting data in asce/desc order
df_sorted = df.sort_values(by='cost', ascending=True)

print(df_sorted)

         country  order_value_EUR       cost       date     category  \
422       Sweden         15100.57   12113.68 2019-02-20        Games
275       France         16388.90   13430.70 2020-03-15  Electronics
17        Sweden         15817.05   13743.44 2019-10-03     Clothing
971  Netherlands              NaN   14102.75 2020-07-02     Clothing
138       Sweden         17524.02   14122.61 2020-12-02        Books
..           ...              ...        ...        ...          ...
766       Sweden        325331.99  264592.51 2019-12-23        Games
242   Luxembourg        312928.72  270401.71 2019-12-12       Beauty
413  Netherlands        353925.06  287528.72 2020-04-12     Clothing
84       Ireland        361182.87  288368.40 2019-02-12        Books
986           UK        383996.76  304701.43 2019-12-19        Other

                 customer_name    sales_manager           sales_rep  \
422  Murray, Reichel and Nolan     Maxie Marrow  Tarrah Castelletti
275              West-Cummings    Othello Bowes        Crysta Halls
17                    Kihn Inc     Maxie Marrow        Anita Woakes
971             Johns and Sons    Denice Amberg      Nero Harbisher
138            Goldner-Dibbert     Maxie Marrow       Madelon Bront
..                         ...              ...                 ...
766      Altenwerth-Konopelski     Maxie Marrow       Caro Morfield
242      Altenwerth-Konopelski         Ilsa Kob  Jocelyn Laurentino
413            Corwin and Sons    Denice Amberg      Nero Harbisher
84                 Smith Group  Glenine Suttaby    Bunnie Tonbridge
986             Johns and Sons  Jessamine Apark        Winny Agnolo

    device_type    order_id
422          PC  89-2424262
275          PC  30-9690927
17           PC  26-9787272
971          PC  38-5910704
138      Mobile  02-3364199
..          ...         ...
766      Mobile  57-4142025
242      Tablet  98-5257166
413          PC  36-2694099
84           PC  44-1953194
986          PC  42-7823733

[1000 rows x 10 columns]

In [42]:
#sorting data in asce/desc order
df_sorted = df.sort_values(by='customer_name', ascending=True)

print(df_sorted)

      country  order_value_EUR       cost       date     category  \
833  Bulgaria        149372.32  130611.16 2020-12-20  Electronics
73   Portugal         41805.53   33352.45 2019-03-23   Appliances
677  Portugal         74364.46   60145.98 2020-01-21     Clothing
749    Sweden         33617.03   26614.60 2020-07-04   Appliances
25   Portugal        121928.48   98408.48 2019-09-19     Clothing
..        ...              ...        ...        ...          ...
381  Portugal        134807.18  108047.95 2020-12-29       Beauty
697    Sweden         97063.22   78067.95 2019-10-19   Appliances
143  Portugal         90994.31   72540.66 2020-09-05  Electronics
32     Sweden         94085.50   77498.23 2020-01-19  Electronics
795    France         32661.62   27922.42 2020-08-02  Electronics

                customer_name    sales_manager            sales_rep  \
833  Abbott, Roberts and Torp      Charil Alpe      Shermy McGready
73   Abbott, Roberts and Torp  Celine Tumasian       Brynn Dempster
677     Altenwerth-Konopelski  Celine Tumasian         Aurelie Wren
749     Altenwerth-Konopelski     Maxie Marrow        Madelon Bront
25      Altenwerth-Konopelski  Celine Tumasian       Brynn Dempster
..                        ...              ...                  ...
381  Zieme, Bailey and Herzog  Celine Tumasian        Corene Shirer
697  Zieme, Bailey and Herzog     Maxie Marrow        Madelon Bront
143  Zieme, Bailey and Herzog  Celine Tumasian       Brynn Dempster
32   Zieme, Bailey and Herzog     Maxie Marrow        Caro Morfield
795  Zieme, Bailey and Herzog    Othello Bowes  Amelina Piscopiello

    device_type    order_id
833      Mobile  63-6848448
73       Tablet  27-7169008
677      Mobile  42-1879788
749          PC  49-8489293
25       Mobile  58-2028009
..          ...         ...
381          PC  76-2368068
697      Tablet  50-0376562
143          PC  09-7835975
32           PC  34-1570975
795          PC  24-7300640

[1000 rows x 10 columns]

In [44]:
#sorting data in asce/desc order
df_sorted = df.sort_values(by='cost', ascending=False)

print(df_sorted)

         country  order_value_EUR       cost       date     category  \
986           UK        383996.76  304701.43 2019-12-19        Other
84       Ireland        361182.87  288368.40 2019-02-12        Books
413  Netherlands        353925.06  287528.72 2020-04-12     Clothing
242   Luxembourg        312928.72  270401.71 2019-12-12       Beauty
766       Sweden        325331.99  264592.51 2019-12-23        Games
..           ...              ...        ...        ...          ...
138       Sweden         17524.02   14122.61 2020-12-02        Books
971  Netherlands              NaN   14102.75 2020-07-02     Clothing
17        Sweden         15817.05   13743.44 2019-10-03     Clothing
275       France         16388.90   13430.70 2020-03-15  Electronics
422       Sweden         15100.57   12113.68 2019-02-20        Games

                 customer_name    sales_manager           sales_rep  \
986             Johns and Sons  Jessamine Apark        Winny Agnolo
84                 Smith Group  Glenine Suttaby    Bunnie Tonbridge
413            Corwin and Sons    Denice Amberg      Nero Harbisher
242      Altenwerth-Konopelski         Ilsa Kob  Jocelyn Laurentino
766      Altenwerth-Konopelski     Maxie Marrow       Caro Morfield
..                         ...              ...                 ...
138            Goldner-Dibbert     Maxie Marrow       Madelon Bront
971             Johns and Sons    Denice Amberg      Nero Harbisher
17                    Kihn Inc     Maxie Marrow        Anita Woakes
275              West-Cummings    Othello Bowes        Crysta Halls
422  Murray, Reichel and Nolan     Maxie Marrow  Tarrah Castelletti

    device_type    order_id
986          PC  42-7823733
84           PC  44-1953194
413          PC  36-2694099
242      Tablet  98-5257166
766      Mobile  57-4142025
..          ...         ...
138      Mobile  02-3364199
971          PC  38-5910704
17           PC  26-9787272
275          PC  30-9690927
422          PC  89-2424262

[1000 rows x 10 columns]